### ISSUE TITLE
Scrolls back to the previously first invalid after correcting input

### ISSUE THREAD

**Issue by ux-engineer** [Ismaestro/ngx-scroll-to-first-invalid#1]
Just started using this package and noticed that the form scrolls back to the previously first invalid even after I've corrected that input's data.

**Comment by Ismaestro** [comment]
The library looks for all the invalid inputs (ng-invalid). Check the example [here](https://ismaestro.github.io/ngx-scroll-to-first-invalid/) please or provide a repo to reproduce the problem...

**Comment by ux-engineer** [comment]
Thanks for explanation, got it solved!
