### ISSUE TITLE
Not working with angular 7

### ISSUE THREAD

**Issue by airasyaqub** [Ismaestro/ngx-scroll-to-first-invalid#10]
I have followed the same steps as mentioned in docs. Installed the package and used the directive in form-group. Its not working. What am I doing wrong ?
```
<form [formGroup]="form" #gsForm="ngForm" (ngSubmit)="saveSettings()" ngxScrollToFirstInvalid>

// form controls in between

</form>
```

**Comment by Ismaestro** [comment]
Hello!

I'm thinking it could be a problem with the variable names. Can you try this:
```
#form="ngForm" [formGroup]="yourFormNotNamedForm"
```

If it persists, just provide me a plunker or something and I will help you!

BR
Isma
