### ISSUE TITLE
Not working with Ionic 3

### ISSUE THREAD

**Issue by sukanyaevon** [Ismaestro/ngx-scroll-to-first-invalid#4]
Follwed the steps to implement but it is not working with ionic version 3.20.0. 
Angular Dependencies :- 
Angular CLI: 6.0.8
Node: 10.13.0
OS: darwin x64
Angular: 5.0.0
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8 (cli-only)
@angular-devkit/build-optimizer   0.0.32
@angular-devkit/core              0.6.8 (cli-only)
@angular-devkit/schematics        0.6.8 (cli-only)
@schematics/angular               0.6.8 (cli-only)
@schematics/update                0.6.8 (cli-only)
rxjs                              5.5.11
typescript                        2.4.2
webpack                           3.12.0

**Comment by Ismaestro** [comment]
This library should be agnostic to Ionic, if you have a form and you have followed the required steps it should work. Can you provide a repo or a stackblitz?
