### ISSUE TITLE
NOT working on Angular 16

### ISSUE THREAD

**Issue by gayathri33** [Ismaestro/ngx-scroll-to-first-invalid#45]
When I tried to upgrade my angular application from  15 to 16 I am getting the below error
npm error Could not resolve dependency:
npm error peer @angular/common@"6.x || 7.x || 8.x || 9.x || 10.x || 11.x || 12.x || 13.x || 14.x || 15.x" from @ismaestro/ngx-scroll-to-first-invalid@15.0.0
npm error node_modules/@ismaestro/ngx-scroll-to-first-invalid

**Comment by rtpHarry** [comment]
Me too.

You can skip the compatibility check by using `--legacy-peer-deps` eg:

```
npm i @ismaestro/ngx-scroll-to-first-invalid --save --legacy-peer-deps
```

I don't know if there are any other issues though as I was working on an ionic app and then realised that it does scrolling differently.

**Comment by Ismaestro** [comment]
I've updated the library to work with the oldest Angular version (18).
