### ISSUE TITLE
Not working with Angular 8

### ISSUE THREAD

**Issue by aram-m** [Ismaestro/ngx-scroll-to-first-invalid#5]
Cannot update our project, because packages have conflicting dependencies.

**Comment by Ismaestro** [comment]
Hello!

Can you provide more info and context? I have successfully upgrade [this project](https://github.com/Ismaestro/angular8-example-app) with the library and no error appeared.

**Comment by aram-m** [comment]
Hello, thank you for your response.
after running ng update I got this message.

 Package "@ismaestro/ngx-scroll-to-first-invalid" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.1").

**Comment by Ismaestro** [comment]
Ok! Let me solve it you should have a new version in an hour or so...

**Comment by aram-m** [comment]
Thanks!

**Comment by Ismaestro** [comment]
I have released a new version 3.0.0, can you check it out?

Thanks!!

**Comment by aram-m** [comment]
It works!!!
